// Generated by reverse-pull search and verified with a push-optimal BFS solver (scratch cl-soko-*.mjs).
// Legend: # wall, _ void, space floor, . goal, @ player, $ crate, * crate on goal, + player on goal.
// par = moves of the push-optimal solution found by the solver.

export type SokobanLevel = { map: string; pushes: number; par: number }

export const LEVELS: SokobanLevel[] = [
  { pushes: 1, par: 1, map: '#####\n#@$.#\n#####' },
  { pushes: 1, par: 2, map: '#######\n# @ $.#\n#######' },
  { pushes: 2, par: 6, map: '######\n#    #\n#.@$ #\n#    #\n######' },
  { pushes: 3, par: 13, map: '########\n#  .   #\n# @$$  #\n#  .   #\n########' },
  { pushes: 7, par: 34, map: '#########\n#   .   #\n#  $ $  #\n# # @ # #\n# . $ . #\n#########' },
  { pushes: 12, par: 25, map: '########\n# .    #\n# .    #\n#      #\n### $$ #\n__# #@ #\n__######' },
  { pushes: 13, par: 36, map: '########\n#. ##  #\n# .#   #\n#      #\n#   $$ #\n# # @# #\n########' },
  { pushes: 14, par: 84, map: '#######_\n#   # ##\n# $  $@#\n# #  . #\n#      #\n# ##  .#\n########' },
  { pushes: 16, par: 54, map: '########\n# ##   #\n# ## $@#\n#    $##\n# .    #\n# .  ###\n######__' },
  { pushes: 14, par: 29, map: '########\n#   .  #\n#.     #\n#  ##  #\n# $@$ ##\n# ##  #_\n#######_' },
  { pushes: 11, par: 23, map: '########\n# .    #\n#      #\n###   ##\n###  $##\n#@$.   #\n# ##   #\n########' },
  { pushes: 12, par: 79, map: '########\n#      #\n#    $##\n#.###@#_\n#    $##\n#  .   #\n##     #\n_#######' },
  { pushes: 15, par: 61, map: '__######\n__#   .#\n__#$   #\n###  . #\n# #    #\n#@$    #\n#      #\n########' },
  { pushes: 15, par: 35, map: '########\n#   .. #\n#    ###\n#    ###\n# $ #  #\n#    $@#\n#  # # #\n########' },
  { pushes: 24, par: 57, map: '########\n#  #   #\n# $#   #\n# @#   #\n#.$#   #\n#      #\n#. ## ##\n#######_' },
  { pushes: 17, par: 81, map: '_#######\n_#    .#\n##$    #\n# $  . #\n# ##  ##\n#    $##\n#. ##@ #\n########' },
  { pushes: 17, par: 44, map: '#######_\n#. #  #_\n# $   ##\n# $    #\n#      #\n#$##   #\n#@##. .#\n########' },
  { pushes: 20, par: 66, map: '########\n#  #@  #\n#  $$  #\n#  $   #\n###    #\n__## . #\n___# ..#\n___#####' },
  { pushes: 20, par: 68, map: '########\n# .##  #\n#  ##$ #\n#  ##  #\n#  ## .#\n#   $  #\n#  $+  #\n########' },
  { pushes: 27, par: 71, map: '########\n#. #   #\n#.$    #\n#  #   #\n# $##  #\n#.@# $ #\n# ##   #\n########' },
  { pushes: 17, par: 55, map: '#####____\n# . ##___\n#..  ####\n#       #\n##  $ ###\n#  $  $@#\n#    #  #\n#########' },
  { pushes: 17, par: 49, map: '#########\n# #@#.  #\n# #$   .#\n#       #\n# $ #$. #\n#   #   #\n# ##### #\n###___###' },
  { pushes: 18, par: 41, map: '#########\n#     . #\n#       #\n#.  ## ##\n#   ##.#_\n#$$$## #_\n# @    #_\n########_' },
  { pushes: 19, par: 61, map: '#########\n#  .    #\n#.  #####\n# .#@####\n#   $#  #\n#  $  $ #\n#       #\n#########' },
  { pushes: 30, par: 128, map: '#######__\n#.    #__\n#.   $##_\n#   #  #_\n#.  # $##\n#     $@#\n###     #\n__#######' },
  { pushes: 20, par: 74, map: '#########\n# ##   .#\n#   ##  #\n#  ..   #\n# $   $@#\n# # ##$ #\n# # ##  #\n#########' },
  { pushes: 21, par: 78, map: '#########\n#   ##. #\n#       #\n# $     #\n# ## .. #\n##  $@$ #\n_#   ####\n_#####___' },
  { pushes: 22, par: 84, map: '########_\n#     @##\n#    $$ #\n###  $  #\n###   # #\n#  . ## #\n#..  #  #\n#########' },
  { pushes: 28, par: 90, map: '#########\n# ## .  #\n# #    .#\n# #    ##\n# $$   .#\n# $@##  #\n#   ##  #\n#########' },
  { pushes: 30, par: 88, map: '#########\n# .  .  #\n### ##@ #\n#  ###$ #\n#   ## ##\n# $$    #\n#    .  #\n#########' },
  { pushes: 21, par: 105, map: '#########\n#   ##. #\n#    $@ #\n# ####  #\n# ##    #\n#  #  $##\n# $ . .#_\n########_' },
  { pushes: 23, par: 61, map: '_########\n##  ##  #\n#  . $@##\n#  $$   #\n#  #    #\n#  ##  .#\n#  ## . #\n#########' },
  { pushes: 24, par: 96, map: '#########\n# $    .#\n# $@$   #\n#  ##   #\n# ####  #\n# ## #  #\n#  ..   #\n#########' },
  { pushes: 23, par: 56, map: '#########\n# .     #\n#.      #\n#  # $  #\n#.###$  #\n# ##  $##\n#   ##@ #\n#########' },
  { pushes: 34, par: 101, map: '#########\n#   ##  #\n#   $@  #\n###$    #\n###    .#\n# #$.   #\n#   . ###\n#######__' },
  { pushes: 27, par: 75, map: '#########\n#   .   #\n#      $#\n### . # #\n##### # #\n# @$    #\n#   #$ .#\n#  ##   #\n#########' },
  { pushes: 23, par: 112, map: '__#######\n###@##. #\n# #$    #\n# #  #  #\n#    #  #\n# ##    #\n# ##$.  #\n# $ .   #\n#########' },
  { pushes: 26, par: 109, map: '#######__\n#  ## #__\n# $## ###\n# $@$   #\n#       #\n#   ## .#\n# .     #\n#   ## .#\n#########' },
  { pushes: 24, par: 83, map: '#########\n#    ## #\n# .  ## #\n#       #\n##  ##  #\n# .  #  #\n##  $ $ #\n_###@$. #\n___######' },
  { pushes: 34, par: 106, map: '#########\n#    #  #\n#   ##. #\n#  $@   #\n###$   ##\n__#    ##\n###$.   #\n#    .  #\n#########' },
  { pushes: 26, par: 71, map: '#########\n#    # .#\n#   . . #\n#  ##   #\n#  ##   #\n#@$  ####\n# $$ #___\n#    #___\n######___' },
  { pushes: 24, par: 126, map: '#########\n#       #\n#   $#$ #\n#    $+##\n#  ## ###\n#       #\n###    ##\n__#..  #_\n__######_' },
  { pushes: 24, par: 64, map: '____#####\n___##   #\n___#   .#\n__##    #\n###    .#\n# #     #\n# $$    #\n#@$.  # #\n#########' },
  { pushes: 25, par: 85, map: '_########\n##@     #\n# $   ###\n#  $  ###\n###     #\n###$    #\n#   .  .#\n#  ### .#\n####_####' },
  { pushes: 36, par: 113, map: '#########\n#.  ##  #\n#   $@ .#\n#  #    #\n#. ##  .#\n#   $   #\n# $ $####\n###  #___\n__####___' },
  { pushes: 25, par: 98, map: '########_\n#.  .$@##\n# #$$ $ #\n# # ### #\n#.  ### #\n#    #  #\n#    #  #\n#  .    #\n#########' },
  { pushes: 27, par: 107, map: '########_\n# ##  @##\n# ### $ #\n#.  ##  #\n# $### ##\n#  $ $ ##\n#    . .#\n# .     #\n#########' },
  { pushes: 32, par: 126, map: '########_\n#   #  ##\n#       #\n#. . $  #\n####$@# #\n#  $ ##.#\n# $  ## #\n#    # .#\n#########' },
  { pushes: 29, par: 96, map: '#########\n# . ##  #\n# . ##. #\n#       #\n#   ##  #\n#   $@$ #\n# ## $$ #\n# ### . #\n###_#####' },
  { pushes: 34, par: 104, map: '__#######\n__#.   .#\n__#  .. #\n###     #\n#  $@   #\n#   $ $ #\n# $### ##\n#   ## #_\n########_' },
]

function transform(map: string, variant: number): string {
  let rows = map.split('\n')
  const w = Math.max(...rows.map((r) => r.length))
  rows = rows.map((r) => r.padEnd(w, '_'))
  if (variant & 1) rows = rows.map((r) => [...r].reverse().join(''))
  if (variant & 2) rows = rows.reverse()
  if (variant & 4) rows = Array.from({ length: w }, (_, x) => rows.map((r) => r[x]).join(''))
  return rows.join('\n')
}

/** Level n (1-based). Past the authored set, harder levels return mirrored/rotated (same par). */
export function levelAt(n: number): SokobanLevel {
  if (n <= LEVELS.length) return LEVELS[n - 1]
  const pool = LEVELS.length - 20
  const k = n - LEVELS.length - 1
  const base = LEVELS[20 + (k % pool)]
  const variant = 1 + (Math.floor(k / pool) % 7)
  return { ...base, map: transform(base.map, variant) }
}
