import type { Block, Door, Level, LevelSpec, Side } from './engine'

/**
 * Hand-designed Block Jam boards (1–30). `board` is drawn with its frame: letters in the
 * frame are door cells of that colour (a run of letters = one door), '#' inside = rock.
 * Blocks: colour, top-left `at`, cell offsets "xy xy …", optional outer layer colour,
 * axis lock (h/v), ice count, lock / key. Every board is verified clearable by a solver that
 * uses the real slide/exit rules (greedy exits + search over block relocations).
 */
export type AuthoredBlock = { c: string; at: [number, number]; cells: string; outer?: string; axis?: 'h' | 'v'; ice?: number; lock?: boolean; key?: boolean }
export type AuthoredBoard = { name: string; intro?: string; hard?: boolean; board: string[]; blocks: AuthoredBlock[] }

export const LEVELS: AuthoredBoard[] = [
  // 1
  {
    name: 'Open Door',
    intro: 'drag a block into its matching door',
    board: [
      '.......',
      '.......',
      'a.....b',
      'a.....b',
      '.......',
      '.......',
      '.......',
    ],
    blocks: [
      { c: 'b', at: [1, 4], cells: '10 00' },
      { c: 'a', at: [3, 4], cells: '00' },
      { c: 'a', at: [2, 0], cells: '00' },
    ],
  },
  // 2
  {
    name: 'Slide Along',
    intro: 'blocks slide until they hit something',
    board: [
      '..aa...',
      '.......',
      '.......',
      'c......',
      'c......',
      '.......',
      '.......',
      '....bb.',
    ],
    blocks: [
      { c: 'a', at: [0, 2], cells: '00' },
      { c: 'a', at: [0, 0], cells: '10 00' },
      { c: 'c', at: [1, 4], cells: '00' },
      { c: 'c', at: [3, 4], cells: '00 10' },
      { c: 'a', at: [2, 0], cells: '00 01 02' },
    ],
  },
  // 3
  {
    name: 'Wide Load',
    intro: 'big blocks need wide doors',
    board: [
      '..aaa...',
      '.......b',
      '.......b',
      '.......b',
      '........',
      '........',
      '........',
      '..ccc...',
    ],
    blocks: [
      { c: 'c', at: [0, 5], cells: '00' },
      { c: 'b', at: [2, 0], cells: '00 01 02 12' },
      { c: 'c', at: [4, 0], cells: '00 10 01 11' },
      { c: 'b', at: [3, 0], cells: '00 01' },
      { c: 'c', at: [5, 4], cells: '00' },
      { c: 'c', at: [1, 4], cells: '00 10 01 11' },
      { c: 'b', at: [5, 2], cells: '00' },
    ],
  },
  // 4
  {
    name: 'One Way',
    intro: 'striped blocks slide one way only',
    board: [
      '..aa.bb.',
      'c.......',
      'c.......',
      '........',
      '........',
      '.......d',
      '.......d',
      '........',
      '........',
    ],
    blocks: [
      { c: 'b', at: [4, 3], cells: '00 01' },
      { c: 'b', at: [5, 0], cells: '00' },
      { c: 'c', at: [3, 0], cells: '11 01 10 00', axis: 'h' },
      { c: 'c', at: [2, 0], cells: '00 01' },
      { c: 'b', at: [5, 1], cells: '00 01 02', axis: 'v' },
      { c: 'c', at: [0, 0], cells: '00 01' },
      { c: 'd', at: [1, 4], cells: '00' },
      { c: 'd', at: [5, 5], cells: '00', axis: 'h' },
    ],
  },
  // 5
  {
    name: 'Corner Office',
    intro: 'hard level · beat the clock',
    hard: true,
    board: [
      '.aa..bb.',
      '........',
      'c.......',
      'c..##...',
      '........',
      '.......d',
      '.......d',
      '........',
      '........',
    ],
    blocks: [
      { c: 'b', at: [2, 3], cells: '10 11 12 01' },
      { c: 'a', at: [1, 1], cells: '02 01 00' },
      { c: 'b', at: [4, 2], cells: '00 10' },
      { c: 'a', at: [2, 1], cells: '00 10' },
      { c: 'b', at: [5, 3], cells: '00' },
      { c: 'b', at: [4, 0], cells: '00 01' },
      { c: 'c', at: [0, 1], cells: '00', axis: 'h' },
      { c: 'd', at: [4, 6], cells: '00' },
      { c: 'b', at: [5, 1], cells: '00' },
      { c: 'd', at: [4, 4], cells: '01 00 11 10', axis: 'h' },
    ],
  },
  // 6
  {
    name: 'Rock Garden',
    intro: 'two-colour blocks peel at the outer door',
    board: [
      '..aa..b.',
      '.......b',
      'c...#..b',
      'c.......',
      '..#.....',
      '........',
      '.....#.d',
      '.......d',
      '........',
    ],
    blocks: [
      { c: 'c', at: [0, 1], cells: '10 00 01', outer: 'a' },
      { c: 'b', at: [3, 0], cells: '21 11 10 00', axis: 'h' },
      { c: 'd', at: [1, 5], cells: '00 10 20' },
      { c: 'd', at: [2, 3], cells: '00' },
      { c: 'd', at: [5, 5], cells: '00 01' },
      { c: 'a', at: [5, 3], cells: '00' },
      { c: 'b', at: [5, 0], cells: '00' },
      { c: 'a', at: [0, 0], cells: '00' },
      { c: 'a', at: [2, 1], cells: '00 01' },
    ],
  },
  // 7
  {
    name: 'Deep Freeze',
    intro: 'frozen blocks thaw as others leave',
    board: [
      '.aaa.bb.',
      '........',
      'c.......',
      'c..#....',
      'c.......',
      '....#..d',
      '.......d',
      '........',
      '........',
    ],
    blocks: [
      { c: 'b', at: [4, 0], cells: '00 10 01 11', ice: 2 },
      { c: 'b', at: [2, 1], cells: '00', outer: 'a' },
      { c: 'c', at: [0, 2], cells: '11 01 10 00', axis: 'h' },
      { c: 'd', at: [1, 5], cells: '00' },
      { c: 'd', at: [3, 1], cells: '00' },
      { c: 'd', at: [5, 2], cells: '00 01' },
      { c: 'a', at: [0, 0], cells: '00 01' },
      { c: 'd', at: [4, 4], cells: '10 11 00 01', axis: 'h' },
      { c: 'a', at: [1, 0], cells: '01 00' },
      { c: 'a', at: [2, 0], cells: '00' },
    ],
  },
  // 8
  {
    name: 'Lock & Key',
    intro: 'free the key to open the lock',
    board: [
      '..aa.bb.',
      'c.......',
      'c.......',
      '........',
      '...##...',
      '........',
      '.......d',
      '.......d',
      '........',
    ],
    blocks: [
      { c: 'c', at: [4, 2], cells: '00 01 11', outer: 'b' },
      { c: 'a', at: [3, 0], cells: '02 01 00', lock: true },
      { c: 'd', at: [1, 5], cells: '00 10 01 11', axis: 'h' },
      { c: 'd', at: [4, 4], cells: '10 11 00 01' },
      { c: 'c', at: [0, 2], cells: '00 01 11' },
      { c: 'a', at: [1, 2], cells: '00' },
      { c: 'c', at: [0, 1], cells: '00' },
      { c: 'b', at: [4, 1], cells: '10 00', ice: 3 },
      { c: 'a', at: [1, 1], cells: '00' },
      { c: 'a', at: [1, 0], cells: '00', axis: 'v' },
      { c: 'b', at: [4, 0], cells: '10 00', key: true },
    ],
  },
  // 9
  {
    name: 'Quiet Courtyard',
    intro: 'a breather',
    board: [
      '.aa..bb.',
      '........',
      'c......d',
      'c......d',
      '........',
      '........',
      '........',
      '........',
    ],
    blocks: [
      { c: 'c', at: [1, 4], cells: '20 10 00', outer: 'd' },
      { c: 'a', at: [0, 2], cells: '10 11 00 01', axis: 'v' },
      { c: 'b', at: [5, 3], cells: '00 01 02' },
      { c: 'b', at: [4, 0], cells: '00 10' },
      { c: 'd', at: [3, 2], cells: '10 11 00 01' },
      { c: 'd', at: [5, 1], cells: '00' },
      { c: 'a', at: [0, 0], cells: '00' },
      { c: 'a', at: [1, 1], cells: '00' },
    ],
  },
  // 10
  {
    name: 'Crossfire',
    intro: 'hard level · doors on every wall',
    hard: true,
    board: [
      '..aa..b..',
      'c.......d',
      'c.......d',
      '.........',
      '....#....',
      '.........',
      'e........',
      'e........',
      '..bb..ee.',
    ],
    blocks: [
      { c: 'e', at: [0, 0], cells: '10 11 12 01', outer: 'a' },
      { c: 'c', at: [1, 4], cells: '01 11 21 20', outer: 'e' },
      { c: 'a', at: [1, 3], cells: '11 10 00', axis: 'v' },
      { c: 'b', at: [4, 2], cells: '00' },
      { c: 'd', at: [4, 0], cells: '00 10 01 11', axis: 'h' },
      { c: 'e', at: [4, 2], cells: '01 11 10' },
      { c: 'a', at: [3, 2], cells: '00', ice: 3 },
      { c: 'e', at: [5, 5], cells: '11 10 00', ice: 3 },
      { c: 'd', at: [6, 0], cells: '00' },
      { c: 'a', at: [2, 0], cells: '01 00', axis: 'v' },
      { c: 'e', at: [5, 6], cells: '00', lock: true },
      { c: 'e', at: [4, 5], cells: '00', key: true },
      { c: 'c', at: [0, 0], cells: '00' },
      { c: 'e', at: [0, 5], cells: '00 01' },
    ],
  },
  // 11
  {
    name: 'Peel Party',
    intro: 'layers everywhere',
    board: [
      '..aa.bb..',
      '.........',
      'c.......d',
      'c.......d',
      '.........',
      '.........',
      '.........',
      '.........',
      '...ee....',
    ],
    blocks: [
      { c: 'b', at: [2, 2], cells: '01 00', outer: 'a' },
      { c: 'e', at: [2, 6], cells: '00', axis: 'v' },
      { c: 'd', at: [1, 3], cells: '00 01 11', outer: 'b' },
      { c: 'b', at: [4, 0], cells: '10 11 12 01' },
      { c: 'e', at: [6, 4], cells: '00', outer: 'd' },
      { c: 'd', at: [4, 6], cells: '00', outer: 'e' },
      { c: 'a', at: [1, 1], cells: '00' },
      { c: 'a', at: [3, 1], cells: '00' },
      { c: 'e', at: [3, 3], cells: '00' },
      { c: 'a', at: [1, 0], cells: '00' },
    ],
  },
  // 12
  {
    name: 'Pillars',
    board: [
      '.aa...bb.',
      '.........',
      'c.#...#.d',
      'c.......d',
      '.........',
      '..#...#..',
      '.........',
      '.........',
      '..ee.....',
    ],
    blocks: [
      { c: 'd', at: [5, 3], cells: '00', outer: 'a' },
      { c: 'b', at: [5, 0], cells: '10 00', axis: 'v' },
      { c: 'e', at: [2, 4], cells: '00 01 11' },
      { c: 'c', at: [0, 2], cells: '10 00', axis: 'h' },
      { c: 'e', at: [3, 2], cells: '02 01 00' },
      { c: 'e', at: [0, 5], cells: '10 00 01' },
      { c: 'd', at: [6, 1], cells: '00 01' },
      { c: 'a', at: [0, 1], cells: '00', outer: 'c' },
      { c: 'a', at: [0, 0], cells: '00', ice: 2 },
      { c: 'e', at: [2, 1], cells: '00' },
      { c: 'a', at: [1, 0], cells: '00' },
      { c: 'e', at: [1, 6], cells: '00' },
    ],
  },
  // 13
  {
    name: 'Narrow Gate',
    board: [
      '...a....',
      '........',
      'c......b',
      'c......b',
      '........',
      '...##...',
      '........',
      'd.......',
      '....ee..',
    ],
    blocks: [
      { c: 'e', at: [1, 0], cells: '00', outer: 'a' },
      { c: 'd', at: [5, 6], cells: '00' },
      { c: 'd', at: [4, 2], cells: '00', outer: 'b', lock: true },
      { c: 'c', at: [3, 0], cells: '01 00' },
      { c: 'c', at: [0, 1], cells: '00 01', axis: 'h' },
      { c: 'b', at: [5, 1], cells: '00', ice: 4 },
      { c: 'd', at: [0, 6], cells: '00 10', axis: 'h' },
      { c: 'e', at: [3, 4], cells: '10 11 01 02', ice: 3 },
      { c: 'd', at: [2, 5], cells: '00' },
      { c: 'e', at: [4, 6], cells: '00' },
      { c: 'd', at: [0, 5], cells: '00' },
      { c: 'a', at: [2, 2], cells: '00 01', key: true },
    ],
  },
  // 14
  {
    name: 'Twin Doors',
    board: [
      '.aa..aa..',
      'c........',
      'c.......b',
      '........b',
      '...#.#...',
      '.........',
      'd........',
      'd.......b',
      '...dd....',
    ],
    blocks: [
      { c: 'd', at: [2, 1], cells: '00', outer: 'a' },
      { c: 'b', at: [3, 1], cells: '00 10 11 21', axis: 'h', ice: 4 },
      { c: 'c', at: [0, 1], cells: '00 01', outer: 'a' },
      { c: 'a', at: [5, 0], cells: '00 10 01 11', ice: 3 },
      { c: 'd', at: [4, 6], cells: '00', axis: 'h' },
      { c: 'd', at: [1, 4], cells: '01 11 10' },
      { c: 'd', at: [3, 6], cells: '00' },
      { c: 'a', at: [2, 2], cells: '00' },
      { c: 'b', at: [6, 5], cells: '00' },
      { c: 'a', at: [1, 2], cells: '00' },
      { c: 'a', at: [3, 0], cells: '00' },
      { c: 'a', at: [0, 0], cells: '00', axis: 'v' },
      { c: 'a', at: [4, 0], cells: '00' },
    ],
  },
  // 15
  {
    name: 'Vault',
    intro: 'hard level · crack the vault',
    hard: true,
    board: [
      '..aaa....',
      'b.......c',
      'b.......c',
      '.........',
      '...#.#...',
      '.........',
      '.........',
      'd.......e',
      'd.......e',
      '...fff...',
    ],
    blocks: [
      { c: 'd', at: [5, 0], cells: '00 10', outer: 'c' },
      { c: 'b', at: [3, 1], cells: '00', axis: 'h', lock: true },
      { c: 'e', at: [0, 3], cells: '00 10 11 21', outer: 'f' },
      { c: 'a', at: [3, 6], cells: '00', axis: 'v', ice: 4 },
      { c: 'b', at: [0, 1], cells: '01 00' },
      { c: 'b', at: [0, 0], cells: '11 10 00', axis: 'h', lock: true },
      { c: 'e', at: [4, 4], cells: '21 11 10 00', key: true },
      { c: 'f', at: [4, 7], cells: '20 10 00', outer: 'e' },
      { c: 'a', at: [2, 2], cells: '00' },
      { c: 'd', at: [1, 5], cells: '00' },
      { c: 'd', at: [3, 7], cells: '00' },
      { c: 'd', at: [0, 7], cells: '20 10 00' },
      { c: 'c', at: [3, 2], cells: '20 10 00', ice: 2, key: true },
      { c: 'e', at: [5, 6], cells: '00' },
      { c: 'c', at: [4, 1], cells: '00 10 20' },
      { c: 'd', at: [0, 6], cells: '20 10 00' },
    ],
  },
  // 16
  {
    name: 'Garden Gate',
    intro: 'a breather',
    board: [
      '.aa...b..',
      '.........',
      'c........',
      'c.......d',
      '........d',
      '.........',
      '.........',
      '.........',
      '...ee....',
    ],
    blocks: [
      { c: 'b', at: [2, 0], cells: '00', outer: 'a' },
      { c: 'd', at: [1, 2], cells: '00 10 20 11', axis: 'h' },
      { c: 'a', at: [0, 0], cells: '00' },
      { c: 'd', at: [4, 1], cells: '01 00' },
      { c: 'b', at: [6, 5], cells: '01 00' },
      { c: 'd', at: [4, 2], cells: '01 11 10' },
      { c: 'e', at: [4, 4], cells: '02 01 00' },
      { c: 'c', at: [0, 1], cells: '00' },
      { c: 'd', at: [6, 2], cells: '00' },
      { c: 'c', at: [1, 1], cells: '00 10' },
    ],
  },
  // 17
  {
    name: 'Hourglass',
    board: [
      '..aaa....',
      '.........',
      'b.#...#.c',
      'b..#.#..c',
      '....#....',
      '...#.#...',
      '..#...#..',
      'd.......e',
      '...ff....',
    ],
    blocks: [
      { c: 'c', at: [5, 1], cells: '01 11 10', axis: 'h' },
      { c: 'b', at: [1, 2], cells: '00', axis: 'h' },
      { c: 'a', at: [2, 1], cells: '00', axis: 'v' },
      { c: 'e', at: [0, 6], cells: '00', outer: 'f' },
      { c: 'd', at: [0, 5], cells: '00', ice: 3 },
      { c: 'f', at: [6, 4], cells: '00', outer: 'e' },
      { c: 'f', at: [2, 4], cells: '10 11 12 01' },
      { c: 'b', at: [0, 1], cells: '00', ice: 4 },
      { c: 'a', at: [3, 0], cells: '20 10 00' },
      { c: 'b', at: [0, 2], cells: '00' },
      { c: 'e', at: [4, 5], cells: '00' },
      { c: 'e', at: [4, 6], cells: '00 10' },
      { c: 'a', at: [2, 0], cells: '00' },
    ],
  },
  // 18
  {
    name: 'Clockwork',
    board: [
      '..aa..bb.',
      'f.......c',
      'f.......c',
      '.........',
      '...#.#...',
      '.........',
      'e.......d',
      'e.......d',
      '.........',
    ],
    blocks: [
      { c: 'c', at: [3, 1], cells: '01 00 11 10', outer: 'a' },
      { c: 'c', at: [5, 2], cells: '01 11 10', outer: 'b' },
      { c: 'd', at: [0, 3], cells: '10 00 01', outer: 'e' },
      { c: 'f', at: [0, 1], cells: '00', axis: 'h', ice: 2 },
      { c: 'a', at: [1, 0], cells: '10 11 12 01' },
      { c: 'e', at: [4, 5], cells: '00 10 01 11', axis: 'h', lock: true },
      { c: 'd', at: [6, 6], cells: '00', ice: 2 },
      { c: 'b', at: [4, 0], cells: '11 10 00' },
      { c: 'd', at: [4, 4], cells: '00' },
      { c: 'b', at: [6, 0], cells: '00 01', axis: 'v' },
      { c: 'e', at: [3, 6], cells: '00', key: true },
      { c: 'e', at: [0, 6], cells: '00 10 20' },
      { c: 'e', at: [1, 5], cells: '00 10 20' },
      { c: 'f', at: [1, 0], cells: '00' },
    ],
  },
  // 19
  {
    name: 'Spiral Stair',
    board: [
      '...aa....',
      '.#......b',
      '..#.....b',
      '...#.....',
      '.........',
      'c....#...',
      'c.....#..',
      '.......#.',
      '....dd...',
    ],
    blocks: [
      { c: 'a', at: [1, 6], cells: '00', outer: 'd' },
      { c: 'd', at: [1, 0], cells: '00', outer: 'a' },
      { c: 'c', at: [4, 6], cells: '10 00', outer: 'd' },
      { c: 'c', at: [0, 4], cells: '11 10 00', axis: 'h' },
      { c: 'b', at: [4, 2], cells: '20 10 00 01', ice: 3 },
      { c: 'b', at: [2, 0], cells: '00' },
      { c: 'd', at: [2, 5], cells: '00', ice: 2 },
      { c: 'a', at: [3, 3], cells: '00 01 02', axis: 'v', ice: 2 },
      { c: 'b', at: [4, 1], cells: '00', lock: true },
      { c: 'b', at: [6, 1], cells: '00' },
      { c: 'd', at: [2, 6], cells: '00' },
      { c: 'b', at: [5, 1], cells: '00' },
      { c: 'a', at: [3, 1], cells: '00 01' },
      { c: 'a', at: [2, 1], cells: '00', axis: 'v', key: true },
    ],
  },
  // 20
  {
    name: 'Iron Gate',
    intro: 'hard level · locks and ice',
    hard: true,
    board: [
      '..aa..bb.',
      'f.......c',
      'f.......c',
      '....#....',
      '.........',
      '..#...#..',
      'e.......d',
      'e.......d',
      '...ff....',
    ],
    blocks: [
      { c: 'f', at: [3, 4], cells: '10 00', outer: 'd' },
      { c: 'a', at: [4, 2], cells: '01 11 10', outer: 'b' },
      { c: 'e', at: [2, 5], cells: '01 00', axis: 'h', lock: true },
      { c: 'b', at: [0, 2], cells: '10 11 00 01', outer: 'a' },
      { c: 'b', at: [4, 0], cells: '02 01 00 11' },
      { c: 'd', at: [3, 5], cells: '00', axis: 'h', ice: 4 },
      { c: 'd', at: [4, 5], cells: '10 00 01', axis: 'h', ice: 4 },
      { c: 'c', at: [6, 1], cells: '00', axis: 'h' },
      { c: 'f', at: [0, 0], cells: '00', outer: 'a' },
      { c: 'c', at: [6, 0], cells: '00' },
      { c: 'a', at: [3, 1], cells: '00', lock: true },
      { c: 'e', at: [0, 4], cells: '00 01 11' },
      { c: 'b', at: [5, 0], cells: '00', ice: 4, key: true },
      { c: 'd', at: [5, 6], cells: '00' },
      { c: 'a', at: [1, 0], cells: '01 11 10' },
      { c: 'd', at: [6, 6], cells: '00' },
      { c: 'f', at: [0, 1], cells: '00', key: true },
    ],
  },
  // 21
  {
    name: 'Market Day',
    intro: 'a breather',
    board: [
      '..aaa....',
      '.........',
      'b.......c',
      'b.......c',
      '.........',
      '.........',
      '.........',
      '.........',
      '...dd....',
    ],
    blocks: [
      { c: 'c', at: [5, 1], cells: '11 01 10 00', axis: 'h' },
      { c: 'a', at: [5, 3], cells: '00', outer: 'c' },
      { c: 'c', at: [4, 1], cells: '00', outer: 'a' },
      { c: 'b', at: [0, 2], cells: '00 10 11 21' },
      { c: 'a', at: [3, 0], cells: '00' },
      { c: 'd', at: [2, 4], cells: '00', axis: 'v' },
      { c: 'd', at: [0, 5], cells: '01 00 11 10' },
      { c: 'a', at: [3, 4], cells: '00' },
      { c: 'd', at: [2, 6], cells: '10 00' },
      { c: 'a', at: [0, 0], cells: '20 10 00 01' },
      { c: 'a', at: [3, 1], cells: '00 01 02' },
    ],
  },
  // 22
  {
    name: 'Checkpoint',
    board: [
      '.aa...bb.',
      '.........',
      'c.#.#.#.d',
      'c.......d',
      '.........',
      '..#.#.#..',
      'e........',
      'e........',
      '....ff...',
    ],
    blocks: [
      { c: 'd', at: [2, 3], cells: '00', outer: 'c' },
      { c: 'e', at: [4, 6], cells: '00 10', outer: 'f' },
      { c: 'e', at: [0, 5], cells: '21 11 10 00', ice: 3 },
      { c: 'a', at: [6, 0], cells: '00', outer: 'b' },
      { c: 'b', at: [4, 0], cells: '00 01' },
      { c: 'e', at: [0, 6], cells: '00', axis: 'h' },
      { c: 'b', at: [6, 2], cells: '00' },
      { c: 'a', at: [1, 0], cells: '00', axis: 'v', ice: 3 },
      { c: 'c', at: [4, 2], cells: '00', axis: 'h' },
      { c: 'c', at: [2, 2], cells: '00', lock: true },
      { c: 'a', at: [0, 0], cells: '00 01' },
      { c: 'c', at: [0, 4], cells: '00' },
      { c: 'd', at: [5, 3], cells: '00' },
      { c: 'f', at: [3, 6], cells: '00' },
      { c: 'b', at: [5, 0], cells: '00', key: true },
    ],
  },
  // 23
  {
    name: 'Switchback',
    board: [
      '..aa.....',
      '........b',
      '.####...b',
      '.........',
      '...####..',
      'c........',
      'c........',
      '.........',
      '...dd.ee.',
    ],
    blocks: [
      { c: 'e', at: [6, 3], cells: '00', outer: 'b' },
      { c: 'a', at: [5, 1], cells: '00', outer: 'b' },
      { c: 'd', at: [2, 4], cells: '00', axis: 'v' },
      { c: 'b', at: [3, 0], cells: '00', axis: 'h' },
      { c: 'e', at: [0, 4], cells: '00 10', outer: 'c', lock: true },
      { c: 'b', at: [4, 0], cells: '00 01', ice: 2 },
      { c: 'd', at: [3, 4], cells: '00' },
      { c: 'e', at: [4, 4], cells: '00 01 11', ice: 3 },
      { c: 'c', at: [1, 5], cells: '00 10' },
      { c: 'e', at: [5, 6], cells: '00', axis: 'v', ice: 4 },
      { c: 'e', at: [6, 5], cells: '00 01', key: true },
      { c: 'd', at: [3, 5], cells: '01 00' },
      { c: 'b', at: [6, 1], cells: '00' },
      { c: 'a', at: [1, 0], cells: '10 00', axis: 'v', lock: true },
      { c: 'b', at: [5, 0], cells: '00', key: true },
    ],
  },
  // 24
  {
    name: 'Cross Street',
    board: [
      '...aa....',
      'b.......c',
      'b.......c',
      '....#....',
      '...###...',
      '....#....',
      'd.......e',
      'd.......e',
      '...ff....',
    ],
    blocks: [
      { c: 'b', at: [2, 0], cells: '21 11 01 10', axis: 'h' },
      { c: 'c', at: [3, 5], cells: '10 00 01', outer: 'e' },
      { c: 'c', at: [4, 0], cells: '00', axis: 'h', lock: true },
      { c: 'e', at: [5, 3], cells: '00 10 01 11', outer: 'c' },
      { c: 'd', at: [1, 6], cells: '10 00', axis: 'h' },
      { c: 'e', at: [5, 5], cells: '00 10', axis: 'h', ice: 4 },
      { c: 'b', at: [0, 0], cells: '00', outer: 'a' },
      { c: 'd', at: [1, 4], cells: '10 00', ice: 3 },
      { c: 'a', at: [2, 0], cells: '00' },
      { c: 'd', at: [2, 5], cells: '00', lock: true },
      { c: 'd', at: [1, 5], cells: '00', ice: 4 },
      { c: 'c', at: [5, 0], cells: '00 01 11' },
      { c: 'e', at: [4, 6], cells: '10 00' },
      { c: 'd', at: [0, 3], cells: '00', key: true },
      { c: 'b', at: [1, 1], cells: '00', key: true },
      { c: 'e', at: [6, 6], cells: '00' },
    ],
  },
  // 25
  {
    name: 'Fortress',
    intro: 'hard level · storm the fortress',
    hard: true,
    board: [
      '..aaa....',
      'b.......c',
      'b.......c',
      '..#...#..',
      '.........',
      '..#...#..',
      'd.......e',
      'd.......e',
      '....fff..',
    ],
    blocks: [
      { c: 'c', at: [1, 0], cells: '00 10', axis: 'h' },
      { c: 'a', at: [4, 0], cells: '00 10 20 11', outer: 'c', lock: true },
      { c: 'd', at: [2, 5], cells: '10 00 01', axis: 'h', ice: 3 },
      { c: 'b', at: [2, 1], cells: '00 10', axis: 'h' },
      { c: 'e', at: [4, 5], cells: '11 01 10 00', outer: 'f' },
      { c: 'e', at: [6, 3], cells: '00' },
      { c: 'b', at: [0, 1], cells: '00' },
      { c: 'd', at: [0, 3], cells: '00', outer: 'b' },
      { c: 'd', at: [0, 4], cells: '00 01 11', ice: 3 },
      { c: 'b', at: [1, 1], cells: '00', outer: 'a', lock: true },
      { c: 'd', at: [1, 6], cells: '00' },
      { c: 'e', at: [6, 6], cells: '00' },
      { c: 'c', at: [6, 2], cells: '00' },
      { c: 'b', at: [0, 0], cells: '00' },
      { c: 'f', at: [3, 6], cells: '00', ice: 3 },
      { c: 'e', at: [6, 5], cells: '00', axis: 'h', key: true },
      { c: 'a', at: [3, 0], cells: '00', key: true },
      { c: 'c', at: [6, 1], cells: '00' },
    ],
  },
  // 26
  {
    name: 'Sunday Stroll',
    intro: 'a breather',
    board: [
      '..aa..bb.',
      '.........',
      'c........',
      'c.......d',
      '........d',
      '.........',
      '.........',
      '.........',
      '..ee.....',
    ],
    blocks: [
      { c: 'e', at: [1, 4], cells: '10 11 12 01', axis: 'v' },
      { c: 'c', at: [2, 1], cells: '00', axis: 'h' },
      { c: 'a', at: [5, 0], cells: '10 00', outer: 'b' },
      { c: 'd', at: [2, 3], cells: '21 11 10 00' },
      { c: 'd', at: [4, 2], cells: '10 11 00 01' },
      { c: 'a', at: [0, 3], cells: '00', ice: 2 },
      { c: 'a', at: [3, 0], cells: '00', outer: 'b' },
      { c: 'a', at: [1, 3], cells: '00 01' },
      { c: 'd', at: [5, 5], cells: '00' },
      { c: 'e', at: [1, 6], cells: '00' },
      { c: 'c', at: [0, 1], cells: '10 11 00 01' },
      { c: 'a', at: [2, 0], cells: '00' },
    ],
  },
  // 27
  {
    name: 'Maze Runner',
    board: [
      '..aa..b..',
      'c.....#.b',
      'c.#......',
      '..#..#...',
      '.....#..d',
      'e.#.....d',
      'e.#..#...',
      '.....#...',
      '...ff....',
    ],
    blocks: [
      { c: 'a', at: [3, 4], cells: '10 00', outer: 'd' },
      { c: 'c', at: [4, 1], cells: '00', outer: 'b' },
      { c: 'f', at: [2, 1], cells: '10 11 12 01', ice: 4 },
      { c: 'f', at: [1, 3], cells: '11 10 00', ice: 4 },
      { c: 'f', at: [2, 5], cells: '00 10 01 11' },
      { c: 'a', at: [1, 0], cells: '00', axis: 'v' },
      { c: 'b', at: [6, 0], cells: '00', axis: 'h', lock: true },
      { c: 'e', at: [0, 5], cells: '00' },
      { c: 'e', at: [0, 4], cells: '00', outer: 'c' },
      { c: 'd', at: [5, 5], cells: '00', lock: true },
      { c: 'a', at: [2, 0], cells: '00', ice: 3 },
      { c: 'c', at: [0, 2], cells: '00', key: true },
      { c: 'd', at: [5, 3], cells: '00', axis: 'h' },
      { c: 'd', at: [5, 4], cells: '00 10' },
      { c: 'c', at: [0, 0], cells: '00' },
      { c: 'c', at: [0, 1], cells: '00', key: true },
    ],
  },
  // 28
  {
    name: 'Diamond Mine',
    board: [
      '...aaa...',
      'b.......c',
      'b...#...c',
      '...#.#...',
      '..#...#..',
      '...#.#...',
      'd...#...e',
      'd.......e',
      '...ff....',
    ],
    blocks: [
      { c: 'c', at: [5, 1], cells: '00', outer: 'a' },
      { c: 'b', at: [0, 1], cells: '10 11 00 01' },
      { c: 'e', at: [4, 4], cells: '01 11 21 20' },
      { c: 'd', at: [5, 6], cells: '00', outer: 'f' },
      { c: 'd', at: [0, 5], cells: '10 00 01', axis: 'h', ice: 4 },
      { c: 'e', at: [6, 0], cells: '00 01', outer: 'c' },
      { c: 'f', at: [2, 6], cells: '00', lock: true },
      { c: 'a', at: [4, 0], cells: '00' },
      { c: 'f', at: [2, 5], cells: '00', ice: 2 },
      { c: 'a', at: [2, 1], cells: '00', axis: 'v', ice: 2 },
      { c: 'a', at: [6, 3], cells: '00', outer: 'c' },
      { c: 'b', at: [1, 0], cells: '10 00', axis: 'h' },
      { c: 'a', at: [4, 1], cells: '00', lock: true },
      { c: 'b', at: [0, 0], cells: '00', axis: 'h', key: true },
      { c: 'a', at: [3, 0], cells: '00' },
      { c: 'f', at: [3, 6], cells: '00', key: true },
      { c: 'e', at: [6, 6], cells: '00' },
    ],
  },
  // 29
  {
    name: 'Rush Hour',
    board: [
      '.aa..bb..',
      'f.......c',
      'f.......c',
      '.........',
      '..##.##..',
      '.........',
      'e.......d',
      'e.......d',
      '...ff....',
    ],
    blocks: [
      { c: 'd', at: [0, 4], cells: '21 11 10 00', outer: 'e' },
      { c: 'd', at: [3, 4], cells: '00 10 01 11', ice: 2 },
      { c: 'b', at: [1, 0], cells: '00 10', outer: 'a' },
      { c: 'b', at: [2, 1], cells: '00 10 01 11', outer: 'c' },
      { c: 'd', at: [5, 5], cells: '01 00', axis: 'h' },
      { c: 'e', at: [1, 6], cells: '00', outer: 'f', lock: true },
      { c: 'f', at: [0, 1], cells: '00 01 11', ice: 2 },
      { c: 'e', at: [0, 5], cells: '00 01', axis: 'h' },
      { c: 'b', at: [3, 0], cells: '00 10' },
      { c: 'f', at: [3, 6], cells: '00', axis: 'v', lock: true },
      { c: 'f', at: [2, 6], cells: '00', axis: 'v' },
      { c: 'c', at: [5, 1], cells: '00 10' },
      { c: 'a', at: [0, 0], cells: '00', ice: 2 },
      { c: 'd', at: [6, 6], cells: '00', key: true },
      { c: 'd', at: [6, 4], cells: '00' },
      { c: 'c', at: [5, 0], cells: '00' },
      { c: 'c', at: [6, 0], cells: '00', key: true },
      { c: 'd', at: [6, 5], cells: '00' },
    ],
  },
  // 30
  {
    name: 'Grand Finale',
    intro: 'final boss · every trick at once',
    hard: true,
    board: [
      '...aa....',
      'f.......b',
      'f.#...#.b',
      '.........',
      '...#.#...',
      '.........',
      'e.#...#.c',
      'e.......c',
      '...dd....',
    ],
    blocks: [
      { c: 'e', at: [6, 3], cells: '00', outer: 'a' },
      { c: 'e', at: [5, 6], cells: '00 10', axis: 'h' },
      { c: 'b', at: [6, 0], cells: '00', axis: 'h' },
      { c: 'a', at: [2, 2], cells: '00', axis: 'v', ice: 2 },
      { c: 'c', at: [3, 5], cells: '00', outer: 'a' },
      { c: 'c', at: [0, 4], cells: '10 00', outer: 'd' },
      { c: 'f', at: [0, 5], cells: '00 01', outer: 'e' },
      { c: 'a', at: [2, 0], cells: '01 00', axis: 'v', lock: true },
      { c: 'a', at: [1, 3], cells: '00' },
      { c: 'b', at: [5, 3], cells: '01 00', ice: 2 },
      { c: 'c', at: [3, 6], cells: '00' },
      { c: 'a', at: [3, 1], cells: '02 01 00', key: true },
      { c: 'd', at: [2, 5], cells: '00', lock: true },
      { c: 'a', at: [3, 0], cells: '00', ice: 3 },
      { c: 'd', at: [2, 4], cells: '00' },
      { c: 'f', at: [0, 0], cells: '01 00', key: true },
      { c: 'b', at: [4, 2], cells: '00' },
      { c: 'd', at: [2, 6], cells: '00' },
    ],
  },
]

export const AUTHORED = LEVELS.length

const COL = 'abcdef'

/** Build a playable board from the authored data (null past the authored set). */
export function authoredLevel(n: number): Level | null {
  const d = LEVELS[n - 1]
  if (!d) return null
  const H = d.board.length
  const W = d.board[0].length
  const cols = W - 2
  const rows = H - 2
  const rocks: number[] = []
  for (let y = 1; y <= rows; y++) for (let x = 1; x <= cols; x++) if (d.board[y][x] === '#') rocks.push((y - 1) * cols + (x - 1))
  const doors: Door[] = []
  const scan = (side: Side, cells: string[]) => {
    let cur: Door | null = null
    cells.forEach((ch, i) => {
      const color = COL.indexOf(ch)
      if (color < 0) {
        cur = null
        return
      }
      if (cur && cur.color === color && cur.at + cur.len === i) cur.len++
      else {
        cur = { side, at: i, len: 1, color }
        doors.push(cur)
      }
    })
  }
  scan(0, [...d.board[0].slice(1, W - 1)])
  scan(1, d.board.slice(1, H - 1).map((r) => r[W - 1]))
  scan(2, [...d.board[H - 1].slice(1, W - 1)])
  scan(3, d.board.slice(1, H - 1).map((r) => r[0]))
  const blocks: Block[] = d.blocks.map((b, id) => ({
    id,
    cells: b.cells.split(' ').map((s) => [Number(s[0]), Number(s[1])] as [number, number]),
    x: b.at[0],
    y: b.at[1],
    color: COL.indexOf(b.c),
    outer: b.outer ? COL.indexOf(b.outer) : -1,
    axis: b.axis === 'h' ? 1 : b.axis === 'v' ? 2 : 0,
    ice: b.ice ?? 0,
    locked: Boolean(b.lock),
    key: Boolean(b.key),
    gone: false,
  }))
  const hard = Boolean(d.hard)
  const layered = blocks.filter((b) => b.outer >= 0).length
  const locks = blocks.filter((b) => b.locked).length
  const spec: LevelSpec = {
    n,
    cols,
    rows,
    colors: new Set(doors.map((o) => o.color)).size,
    blocks: blocks.length,
    rocks: rocks.length,
    axis: blocks.filter((b) => b.axis).length,
    layered,
    ice: blocks.filter((b) => b.ice).length,
    locks,
    hard,
    time: Math.round(20 + blocks.length * (hard ? 5 : 6.5) + layered * 4 + locks * 4),
    intro: d.intro,
  }
  return { spec, blocks, doors, rocks }
}
